export default{
  session_id: "",
  owner: "",
  __comment1: "Replace with you number, my lovely user",
  global_owner: "cyber_cyphers",
  __comment2: "do not touch the global_owner part. I beg of you.",
  email: "cybercyphers2008@gmail.com",
  __comment3: "email address to receive  information and reset option s. very important ",
  user_phone: "",
  __comment4: "enter you number without the + symbol to pair",
  prefix: ".",
  __comment5: "The prefix you bot will be listening to for command",
  private: true,
  __comment6: "this will allow me to automatically apply new updates from cyber_cyphers for better functionality and improved or fixed bugs in my code",
  automatic_updates: true,
  already_configured: true,
  __comment7: "This option enables the startup script { index.js } to configure its tokens, it automatically toggle as set times",
  allowBugsReview: true,
  antidelete: true
}
